stages:
  feature_engineering:
    cmd: |
      python3 scripts/data_processing.py --stage preprocess --input data/raw/MachineLearningRating_v3.csv --output data/preprocessed/feature_engineered_data.csv
    deps:
      - data/raw/MachineLearningRating_v3.csv
    outs:
      - data/preprocessed/feature_engineered_data.csv

  handle_missing_values:
    cmd: |
      python3 scripts/data_processing.py --stage handle_missing_values --input data/preprocessed/feature_engineered_data.csv --output data/preprocessed/no_missing_values.csv
    deps:
      - data/preprocessed/feature_engineered_data.csv
    outs:
      - data/preprocessed/no_missing_values.csv

  encode_data:
    cmd: |
      python3 scripts/data_processing.py --stage encode_data --input data/preprocessed/no_missing_values.csv --output data/preprocessed/encoded_data.csv
    deps:
      - data/preprocessed/no_missing_values.csv
    outs:
      - data/preprocessed/encoded_data.csv

  scale_data:
    cmd: |
      python3 scripts/data_processing.py --stage scale_data --input data/preprocessed/encoded_data.csv --output data/preprocessed/scaled_data.csv
    deps:
      - data/preprocessed/encoded_data.csv
    outs:
      - data/preprocessed/scaled_data.csv
